### ISSUE TITLE
ServiceUtils.mapPagedAxiosResponse returns rowCount of current result set, not total result set

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.JavaScript.Core#15]
Looks like this was lost in translation when porting

`rowCount` on the `ServiceResponse` is being set from `data.resultObject.length` (row count of the currently returned set), when it really should be set off of `data.rowCount` (total result set of the current query) which matches our C# `PagedResult` model:

https://github.com/AndcultureCode/AndcultureCode.JavaScript.Core/blob/master/src/utilities/service-utils.ts#L138
```
    return {
        results: new ResultRecord<TRecord[]>(data),
        resultObjects: resultObjects,
        rowCount: data?.resultObject?.length ?? 0, // should be rowCount: data.rowCount,
        status: axiosResponse.status,
    };
```

https://github.com/AndcultureCode/AndcultureCode.CSharp.Core/blob/master/src/AndcultureCode.CSharp.Core/Models/Errors/PagedResult.cs
```
        public T                          ResultObject   { get; set; }
        public long                       RowCount       { get; set; }
```

I think this transformation method is used for all `list` service calls, whether or not the controller is returning paged results. Maybe it would be best to default it to the current calculated value if `data.rowCount` is null or undefined.

**Comment by wintondeshong** [comment]
Yikes, yeah this needs fixed. Odd, I pulled it straight from latest 🤷‍♂️

**Comment by brandongregoryscott** [comment]
Might've been some accidental refactoring when I was originally porting it
over. I have a fix for it on my fork, I can update or write tests for it
and get it up soon 👍

–––
*brandon scott*
software engineer [image: asterisk]
[image: andculture] <https://andculture.com/>
andculture.com

717.233.2881
[image: asterisk] software engineer
–––
This e-mail message and any documents attached to it are confidential and
may contain information that is protected from disclosure by various
federal and state laws, including the HIPAA privacy rule (45 C.F.R., Part
164). andculture is not liable for the use, dissemination, forwarding,
printing or copying of this message without the sender's written
permission. Accordingly, if you have received this message in error, please
notify the sender immediately by return e-mail or call 717-233-2881, and
then permanently delete this message and any attachments and associated
information.

**Comment by brandongregoryscott** [comment]
Might've been some accidental refactoring when I was originally porting it over. I have a fix for it on my fork, I can update or write tests for it and get it up soon 👍

**Comment by wintondeshong** [comment]
It's all good. The rate at which we are getting code up in these repositories lately is worth it.
