### ISSUE TITLE
Port `TargetTypes` enum

### ISSUE THREAD

**Issue by zball** [AndcultureCode/AndcultureCode.JavaScript.Core#39]
Port an enum for Anchor TargetTypes:

export enum TargetTypes {
    Blank = "_blank",
    Parent = "_parent",
    Self = "_self",
    Top = "_top",
}

**Comment by brandongregoryscott** [comment]
Published with [v0.1.9](https://github.com/AndcultureCode/AndcultureCode.JavaScript.Core/releases/tag/v0.1.9)
