### ISSUE TITLE
Export intersection function from lodash

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.JavaScript.Core#44]
It'd be nice to have at least one of the intersections functions from lodash. The `intersectionWith` function seems to give the most flexibility with a comparator function for each element:

https://lodash.com/docs/4.17.15#intersectionWith

```JS
var objects = [{ 'x': 1, 'y': 2 }, { 'x': 2, 'y': 1 }];
var others = [{ 'x': 1, 'y': 1 }, { 'x': 1, 'y': 2 }];
 
_.intersectionWith(objects, others, _.isEqual);
// => [{ 'x': 1, 'y': 2 }]
```

Forward this function from `CollectionUtils`

**Comment by dtnhinh** [comment]
Can I be assigned to this issue? Thank you
