### ISSUE TITLE
Port over Typescript implementation of Do.Try pattern

### ISSUE THREAD

**Issue by mrjones2014** [AndcultureCode/AndcultureCode.JavaScript.Core#47]
A Typescript implementation of the `Do.Try` pattern was recently added to one of the client projects. Could be pretty useful to port over into this project.

**Comment by brandongregoryscott** [comment]
Published with [v0.2.0](https://github.com/AndcultureCode/AndcultureCode.JavaScript.Core/releases/tag/v0.2.0)
