### ISSUE TITLE
Write tests for CollectionUtils

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode.JavaScript.Core#6]
Using CodeCov results as a guide, improve tests for various functions in CollectionUtils 

https://codecov.io/gh/AndcultureCode/AndcultureCode.JavaScript.Core/src/master/src/utilities/collection-utils.ts

**Comment by brandongregoryscott** [comment]
Planning on pairing with @SaidShah on this tomorrow 👍
