### ISSUE TITLE
Consider removing peer dependency usage directly in exported objects

### ISSUE THREAD

**Issue by KevinBusch** [AndcultureCode/AndcultureCode.JavaScript.Core#69]
Where possible, we should consider updating any currently exported module objects that reference peer dependencies directly and instead reference a private function that calls the peer dependency. This will eliminate errors if a consumer does not reference the peer dependency library before referencing the global distribution package

**Comment by dtnhinh** [comment]
Can I be assigned to this issue? Thanks
