### ISSUE TITLE
Write tests for ServiceUtils

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode.JavaScript.Core#7]
Using CodeCov results as a guide, improve unit tests for ServiceUtils

https://codecov.io/gh/AndcultureCode/AndcultureCode.JavaScript.Core/src/master/src/utilities/service-utils.ts

**Comment by HeyKos** [comment]
Looks like there is far more coverage now (over 95%) then there was when this issue was created. I'll get it to 100%, but certainly not as high of a need as I thought when I jumped in 😄

**Comment by HeyKos** [comment]
Additional unit test added, which bumped the test coverage for ServiceUtils up to 100%.
