### ISSUE TITLE
Publish process not publishing global distribution file(s)

### ISSUE THREAD

**Issue by cspath1** [AndcultureCode/AndcultureCode.JavaScript.Core#74]
Recently, we added support for non-modular front-end applications to utilize our `AndcultureCode.Javascript.Core` project via a global distribution. As it turns out, while a `dist-global` folder is generated as part of the `npm run build` command, the `npm publish` command is not utilizing this folder during the publish process.

**Comment by brandongregoryscott** [comment]
Should be published [v0.3.5](https://github.com/AndcultureCode/AndcultureCode.JavaScript.Core/releases/tag/v0.3.5) - let me know if you're still having issues and we can open this back up 👍
