### ISSUE TITLE
Update rosie/jest to be prod deps, or exclude tests/mocks/factories from dist

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.JavaScript.Core#8]
Running into a similar issue to [AndcultureCode.JavaScript.React#7](https://github.com/AndcultureCode/AndcultureCode.JavaScript.React/issues/7) when importing this package - I think we need to remove the exports for `tests/` and `__mocks__`, or update `rosie` and `jest` to be production dependencies. I'm not sure there's really a benefit to exporting these, unless we find them useful to leverage across packages for their respective testing suites. 

At that point, it might be worth breaking out into a separate testing package, similar to our C# testing package.

**Comment by wintondeshong** [comment]
@brandongregoryscott Yeah, the goal was to eventually here loop around and extract it to the testing package. I'm just now changing gears to push through frontend actors more so I'll start by creating the AndcultureCode.JavaScript.Testing package which should resolve this issue. Thank you!

**Comment by wintondeshong** [comment]
@brandongregoryscott published in version v0.0.7. Give this a whirl and if it persists, re-open the issue.
