### ISSUE TITLE
StringUtils.isEmpty type guard types value as 'never' when false

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.JavaScript.Core#82]
Attempted upgrading a client project to `0.4.0` to leverage the new type guards and I believe this is incorrect:

![image](https://user-images.githubusercontent.com/11774799/101355863-365f4e00-3865-11eb-9132-fb29cade8622.png)

If `StringUtils.isEmpty` returns true, it should probably act like the `CollectionUtils.isEmpty` function and return `value is undefined`. Otherwise, when it is _false_, the TS compiler thinks it is `never` and you need to force it as non-null with `!`

![image](https://user-images.githubusercontent.com/11774799/101355998-6dcdfa80-3865-11eb-9c05-a97515f238a6.png)

**Comment by nhinhdao** [comment]
I will look into this

**Comment by brandongregoryscott** [comment]
Thanks @nhinhdao! No rush, I was just excited to use the new guards! 😂

**Comment by brandongregoryscott** [comment]
@nhinhdao How's this coming? I am holding back on pushing out a new version w/ the JSDoc + `RecordUtils` type guard since it won't be of much use with the way the type guard for `isEmpty` currently stands

**Comment by nhinhdao** [comment]
Hey @brandongregoryscott, sorry for holding you back. I actually haven't looked into this issue. Let me get back to you this afternoon on this.

**Comment by nhinhdao** [comment]
@brandongregoryscott I have found the workaround for this case by using **literal type** for string;
 
![image](https://user-images.githubusercontent.com/27240955/102921665-be934500-445a-11eb-804e-d16a1beece22.png)

this type predicate will narrow **value** to be `null | undefined | ''` which works well for this case

**Comment by brandongregoryscott** [comment]
Woah, that's awesome 👍 Is it actually bound to `null | undefined | ''` with the type guard of `value is ''`? As long as we don't have to start non-null asserting after `isEmpty` returns false, then we should be good to go. Do you want to send out a PR for this, or would you like me to pick it up?

**Comment by nhinhdao** [comment]
Yup. `value?: string` with type predicate `value is ""` is equivalent to `value: null | undefined | string` with type predicate `value is null | undefined | ''` so the optional parameter actually helps taking care of that. PR is coming in a bit
