### ISSUE TITLE
Reevaluate production vs. peer/dev dependencies

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.JavaScript.Core#95]
After some recent debugging during the attempted axios upgrade, and looking at other packages for reference, @wintondeshong and I are suspecting that the current `dependencies` list is incorrect, and most (if not all) of them should be listed as `peerDependencies` and `devDependencies`. This leaves it up to the consumer to install them if they are using external libraries we are referencing, such as `axios`, `react`, `react-dom`, etc, while maintaining copies for local development. 

This should alleviate potential issues with multiple versions of the same package, ie having multiple instances of `axios` configured differently, or React errors from running multiple instances. It should also remove the need to re-export `react-router-dom` components, which was a workaround solution to use our routing abstraction in another project. 

In addition to specifying these external libraries as peer dependencies, we should lighten the version requirement on them so consumers are not locked in to just the specific version of the package we are using for development, which is rigid and can cause dependency update nightmare. Use your best judgement for specifying a range or minimum version requirement based on the versions we're currently pulling in. This may need to be tweaked as the new package structure rolls out.

Because this is a pretty major change to the way the package is being used currently, we'll want to make sure we update the readme to reflect this new behavior.

**Comment by brandongregoryscott** [comment]
Just noting this here for future reference - I stumbled upon a package called [codependency](https://github.com/Wizcorp/codependency) that offers a similar approach to what I was trying to accomplish with 'optional' peer dependencies. For packages that consumers may never need to use (thinking `i18next` or `humanize-plus`, for example), we could update the imports where they are currently located to be something along the lines of...

```ts
import HumanizeModule from "humanize-plus"; // Importing just the type, this does not emit a require(...)
import codependency from "codependency";
const requirePeer = codependency.get("andculturecode-javascript-core");
// Does not throw an error on import, but does return undefined if consumer does not have humanize-plus installed
const Humanize = requirePeer("humanize-plus", { optional: true }) as typeof HumanizeModule; 

...
const pluralize = (
    number: number,
    singular?: string,
    plural?: string
): string => Humanize.pluralize(number, singular, plural);
```

We could also move the `requirePeer` call to where the dep is actually called, and let it throw an error at runtime (by removing the `{ optional: true }` object) - which might be more obvious to a consumer when they are attempting to use a function we provide that relies on an external, optional dependency.

It sounds like for now, we are OK with having consumers install the few external dependencies we have listed, even if they are not planning on using those features. If this becomes too much of a pain, we may want to consider moving in this direction ☝️

**Comment by wintondeshong** [comment]
> Just noting this here for future reference - I stumbled upon a package called [codependency](https://github.com/Wizcorp/codependency) that offers a similar approach to what I was trying to accomplish with 'optional' peer dependencies. For packages that consumers may never need to use (thinking `i18next` or `humanize-plus`, for example), we could update the imports where they are currently located to be something along the lines of...
> 
> ```ts
> import HumanizeModule from "humanize-plus"; // Importing just the type, this does not emit a require(...)
> import codependency from "codependency";
> const requirePeer = codependency.get("andculturecode-javascript-core");
> // Does not throw an error on import, but does return undefined if consumer does not have humanize-plus installed
> const Humanize = requirePeer("humanize-plus", { optional: true }) as typeof HumanizeModule; 
> 
> ...
> const pluralize = (
>     number: number,
>     singular?: string,
>     plural?: string
> ): string => Humanize.pluralize(number, singular, plural);
> ```
> 
> We could also move the `requirePeer` call to where the dep is actually called, and let it throw an error at runtime (by removing the `{ optional: true }` object) - which might be more obvious to a consumer when they are attempting to use a function we provide that relies on an external, optional dependency.
> 
> It sounds like for now, we are OK with having consumers install the few external dependencies we have listed, even if they are not planning on using those features. If this becomes too much of a pain, we may want to consider moving in this direction ☝️

@brandongregoryscott thank you for all the work writing this up, investigations and finding the `codependency` package above. Being able to avoid declaring deps in consumers, despite not needing them, would be awesome! I also think it has minimal impact in terms of code (per examples above and in their repo). I wonder if we can find any other libraries fulfilling the same need? I ask because it appears there are some pretty long outstanding issues with this particular library. If not, we can give it a whirl and see if we are impacted by any of those issues and perhaps take a stab at resolving them.

**Comment by brandongregoryscott** [comment]
@wintondeshong Of course! Glad to dig into it. I will keep digging for other solutions too. Noting here that while I stumbled upon this package separately (typing 'peer dependency' into Github, out of curiosity), I stumbled upon another StackExchange answer this morning that described the same approach and linked to that package. https://softwareengineering.stackexchange.com/a/273576

**Comment by wintondeshong** [comment]
> @wintondeshong Of course! Glad to dig into it. I will keep digging for other solutions too. Noting here that while I stumbled upon this package separately (typing 'peer dependency' into Github, out of curiosity), I stumbled upon another StackExchange answer this morning that described the same approach and linked to that package. https://softwareengineering.stackexchange.com/a/273576

I'm down if we try it out. Looks promising despite some of the outstanding issues. Can see how it goes
